---
# Required by GitHub Action to install additional collection and roles.
collections:
  - name: community.general
    version: "*"
  - name: containers.podman
    version: "*"
  - name: ansible.posix
    version: "*"

  - name: https://github.com/ChunPanYung/ansi_colle-slim_os.git
    type: git
    version: main
  - name: https://github.com/ChunPanYung/ansi_colle-mods.git
    type: git
    version: main
  - name: https://github.com/ChunPanYung/ansi_colle-server.git
    type: git
    version: main
