---
- name: Execute installation with sudo
  become: true
  block:
    - name: Install Neovim and dependencies
      ansible.builtin.dnf:
        name:
          - neovim
          - python3-neovim
          - gcc-c++  # Required by nvim-treesitter
          - lua
          - luarocks

    - name: Install VirtualBox
      ansible.builtin.dnf:
        name: VirtualBox

- name: Install packages from repository
  become: true
  block:
    - name: Install dnf-plugins-core, required by community.general.copr
      ansible.builtin.dnf:
        name: dnf-plugins-core

    - name: Enable lazygit repository
      community.general.copr:
        name: 'atim/lazygit'

    - name: Install utilities
      ansible.builtin.dnf:
        name: lazygit

    - name: Install frameworks and languages
      ansible.builtin.dnf:
        name:
          - dotnet
