---
# tasks file for python
- name: Install following with sudo
  become: true
  block:
    - name: Install python and related packages
      ansible.builtin.package:
        name:
          - gcc
          - python3-pip
          - pipx
          - python3-ipython
          - black
          - pre-commit
          - python3-pytest

    - name: Install following if it is RedHat based OS
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name:
          - python3-devel

    - name: Install following if it is Debian based OS
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name:
          - python3-dev

- name: Install developmental tools
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - git-cliff
    - ruff
    - pdm
